package com.epam.drill.transport.net

import platform.posix.*
import kotlin.native.concurrent.*

actual val EAGAIN_ERROR: Int = EAGAIN

@SharedImmutable
actual val errorsMapping = setOf(
    TcpError(name = "EPERM", id = 1, description = "(Operationnotpermitted) Operation not permitted"),
    TcpError(name = "ENOENT", id = 2, description = "(Nosuchfileordirectory) No such file or directory"),
    TcpError(name = "ESRCH", id = 3, description = "(Nosuchprocess) No such process"),
    TcpError(name = "EINTR", id = 4, description = "(Interruptedsystemcall) Interrupted system call"),
    TcpError(name = "EIO", id = 5, description = "(Input/outputerror) Input/output error"),
    TcpError(name = "ENXIO", id = 6, description = "(Devicenotconfigured) No such device or address"),
    TcpError(name = "E2BIG", id = 7, description = "(Argumentlisttoolong) Argument list too long"),
    TcpError(name = "ENOEXEC", id = 8, description = "(Execformaterror) Exec format error"),
    TcpError(name = "EBADF", id = 9, description = "(Badfiledescriptor) Bad file descriptor"),
    TcpError(name = "ECHILD", id = 10, description = "(Nochildprocesses) No child processes"),
    TcpError(name = "EDEADLK", id = 11, description = "(Resourcedeadlockavoided) Resource temporarily unavailable"),
    TcpError(name = "ENOMEM", id = 12, description = "(Cannotallocatememory) Cannot allocate memory"),
    TcpError(name = "EACCES", id = 13, description = "(Permissiondenied) Permission denied"),
    TcpError(name = "EFAULT", id = 14, description = "(Badaddress) Bad address"),
    TcpError(name = "ENOTBLK", id = 15, description = "(Blockdevicerequired) Block device required"),
    TcpError(name = "EBUSY", id = 16, description = "(Devicebusy) Device or resource busy"),
    TcpError(name = "EEXIST", id = 17, description = "(Fileexists) File exists"),
    TcpError(name = "EXDEV", id = 18, description = "(Cross-devicelink) Invalid cross-device link"),
    TcpError(name = "ENODEV", id = 19, description = "(Operationnotsupportedbydevice) No such device"),
    TcpError(name = "ENOTDIR", id = 20, description = "(Notadirectory) Not a directory"),
    TcpError(name = "EISDIR", id = 21, description = "(Isadirectory) Is a directory"),
    TcpError(name = "EINVAL", id = 22, description = "(Invalidargument) Invalid argument"),
    TcpError(name = "ENFILE", id = 23, description = "(Toomanyopenfilesinsystem) Too many open files in system"),
    TcpError(name = "EMFILE", id = 24, description = "(Toomanyopenfiles) Too many open files"),
    TcpError(name = "ENOTTY", id = 25, description = "(Inappropriateioctlfordevice) Inappropriate ioctl for device"),
    TcpError(name = "ETXTBSY", id = 26, description = "(Textfilebusy) Text file busy"),
    TcpError(name = "EFBIG", id = 27, description = "(Filetoolarge) File too large"),
    TcpError(name = "ENOSPC", id = 28, description = "(Nospaceleftondevice) No space left on device"),
    TcpError(name = "ESPIPE", id = 29, description = "(Illegalseek) Illegal seek"),
    TcpError(name = "EROFS", id = 30, description = "(Read-onlyfilesystem) Read-only file system"),
    TcpError(name = "EMLINK", id = 31, description = "(Toomanylinks) Too many links"),
    TcpError(name = "EPIPE", id = 32, description = "(Brokenpipe) Broken pipe"),
    TcpError(name = "EDOM", id = 33, description = "(Numericalargumentoutofdomain) Numerical argument out of domain"),
    TcpError(name = "ERANGE", id = 34, description = "(Resulttoolarge) Numerical result out of range"),
    TcpError(name = "EAGAIN", id = 35, description = "(Resourcetemporarilyunavailable) Resource deadlock avoided"),
    TcpError(name = "EWOULDBLOCK", id = 35, description = "(Resourcetemporarilyunavailable) File name too long"),
    TcpError(name = "EINPROGRESS", id = 36, description = "(Operationnowinprogress) No locks available"),
    TcpError(name = "EALREADY", id = 37, description = "(Operationalreadyinprogress) Function not implemented"),
    TcpError(name = "ENOTSOCK", id = 38, description = "(Socketoperationonnon-socket) Directory not empty"),
    TcpError(
        name = "EDESTADDRREQ",
        id = 39,
        description = "(Destinationaddressrequired) Too many levels of symbolic links"
    ),
    TcpError(name = "EMSGSIZE", id = 40, description = "(Messagetoolong) Unknown error 41"),
    TcpError(name = "EPROTOTYPE", id = 41, description = "(Protocolwrongtypeforsocket) No message of desired type"),
    TcpError(name = "ENOPROTOOPT", id = 42, description = "(Protocolnotavailable) Identifier removed"),
    TcpError(name = "EPROTONOSUPPORT", id = 43, description = "(Protocolnotsupported) Channel number out of range"),
    TcpError(name = "ESOCKTNOSUPPORT", id = 44, description = "(Sockettypenotsupported) Level 2 not synchronized"),
    TcpError(name = "EOPNOTSUPP", id = 45, description = "(Operationnotsupported) Level 3 halted"),
    TcpError(name = "ENOTSUP", id = 45, description = "(Operationnotsupported) Level 3 reset"),
    TcpError(name = "EPFNOSUPPORT", id = 46, description = "(Protocolfamilynotsupported) Link number out of range"),
    TcpError(
        name = "EAFNOSUPPORT",
        id = 47,
        description = "(Addressfamilynotsupportedbyprotocolfamily) Protocol driver not attached"
    ),
    TcpError(name = "EADDRINUSE", id = 48, description = "(Addressalreadyinuse) No CSI structure available"),
    TcpError(name = "EADDRNOTAVAIL", id = 49, description = "(Can'tassignrequestedaddress) Level 2 halted"),
    TcpError(name = "ENETDOWN", id = 50, description = "(Networkisdown) Invalid exchange"),
    TcpError(name = "ENETUNREACH", id = 51, description = "(Networkisunreachable) Invalid request descriptor"),
    TcpError(name = "ENETRESET", id = 52, description = "(Networkdroppedconnectiononreset) Exchange full"),
    TcpError(name = "ECONNABORTED", id = 53, description = "(Softwarecausedconnectionabort) No anode"),
    TcpError(name = "ECONNRESET", id = 54, description = "(Connectionresetbypeer) Invalid request code"),
    TcpError(name = "ENOBUFS", id = 55, description = "(Nobufferspaceavailable) Invalid slot"),
    TcpError(name = "EISCONN", id = 56, description = "(Socketisalreadyconnected) Unknown error 58"),
    TcpError(name = "ENOTCONN", id = 57, description = "(Socketisnotconnected) Bad font file format"),
    TcpError(name = "ESHUTDOWN", id = 58, description = "(Can'tsendaftersocketshutdown) Device not a stream"),
    TcpError(name = "ETOOMANYREFS", id = 59, description = "(Toomanyreferences:can'tsplice) No data available"),
    TcpError(name = "ETIMEDOUT", id = 60, description = "(Operationtimedout) Timer expired"),
    TcpError(name = "ECONNREFUSED", id = 61, description = "(Connectionrefused) Out of streams resources"),
    TcpError(name = "ELOOP", id = 62, description = "(Toomanylevelsofsymboliclinks) Machine is not on the network"),
    TcpError(name = "ENAMETOOLONG", id = 63, description = "(Filenametoolong) Package not installed"),
    TcpError(name = "EHOSTDOWN", id = 64, description = "(Hostisdown) Object is remote"),
    TcpError(name = "EHOSTUNREACH", id = 65, description = "(Noroutetohost) Link has been severed"),
    TcpError(name = "ENOTEMPTY", id = 66, description = "(Directorynotempty) Advertise error"),
    TcpError(name = "EPROCLIM", id = 67, description = "(Toomanyprocesses) Srmount error"),
    TcpError(name = "EUSERS", id = 68, description = "(Toomanyusers) Communication error on send"),
    TcpError(name = "EDQUOT", id = 69, description = "(Discquotaexceeded) Protocol error"),
    TcpError(name = "ESTALE", id = 70, description = "(StaleNFSfilehandle) Multihop attempted"),
    TcpError(name = "EREMOTE", id = 71, description = "(Toomanylevelsofremoteinpath) RFS specific error"),
    TcpError(name = "EBADRPC", id = 72, description = "(RPCstructisbad) Bad message"),
    TcpError(name = "ERPCMISMATCH", id = 73, description = "(RPCversionwrong) Value too large for defined data type"),
    TcpError(name = "EPROGUNAVAIL", id = 74, description = "(RPCprog.notavail) Name not unique on network"),
    TcpError(name = "EPROGMISMATCH", id = 75, description = "(Programversionwrong) File descriptor in bad state"),
    TcpError(name = "EPROCUNAVAIL", id = 76, description = "(Badprocedureforprogram) Remote address changed"),
    TcpError(name = "ENOLCK", id = 77, description = "(Nolocksavailable) Can not access a needed shared library"),
    TcpError(name = "ENOSYS", id = 78, description = "(Functionnotimplemented) Accessing a corrupted shared library"),
    TcpError(name = "EFTYPE", id = 79, description = "(Inappropriatefiletypeorformat) .lib section in a.out corrupted"),
    TcpError(
        name = "EAUTH",
        id = 80,
        description = "(Authenticationerror) Attempting to link in too many shared libraries"
    ),
    TcpError(name = "ENEEDAUTH", id = 81, description = "(Needauthenticator) Cannot exec a shared library directly"),
    TcpError(
        name = "EIDRM",
        id = 82,
        description = "(Identifierremoved) Invalid or incomplete multibyte or wide character"
    ),
    TcpError(
        name = "ENOMSG",
        id = 83,
        description = "(Nomessageofdesiredtype) Interrupted system call should be restarted"
    ),
    TcpError(name = "EOVERFLOW", id = 84, description = "(Valuetoolargetobestoredindatatype) Streams pipe error"),
    TcpError(name = "ECANCELED", id = 85, description = "(Operationcanceled) Too many users"),
    TcpError(name = "EILSEQ", id = 86, description = "(Illegalbytesequence) Socket operation on non-socket"),
    TcpError(name = "ENOATTR", id = 87, description = "(Attributenotfound) Destination address required"),
    TcpError(name = "EDOOFUS", id = 88, description = "(Programmingerror) Message too long"),
    TcpError(name = "EBADMSG", id = 89, description = "(Badmessage) Protocol wrong type for socket"),
    TcpError(name = "EMULTIHOP", id = 90, description = "(Multihopattempted) Protocol not available"),
    TcpError(name = "ENOLINK", id = 91, description = "(Linkhasbeensevered) Protocol not supported"),
    TcpError(name = "EPROTO", id = 92, description = "(Protocolerror) Socket type not supported"),
    TcpError(name = "ENOTCAPABLE", id = 93, description = "(Capabilitiesinsufficient) Operation not supported"),
    TcpError(name = "ECAPMODE", id = 94, description = "(Notpermittedincapabilitymode) Protocol family not supported")
).associateBy { it.id }